#ifndef SOURIS_PLATFORM_LINUX_INTERFACE_X11_MESSAGE_BOX_MESSAGE_BOX_HPP
#define SOURIS_PLATFORM_LINUX_INTERFACE_X11_MESSAGE_BOX_MESSAGE_BOX_HPP

# include "core/defines.hpp"

SOURIS_PLATFORM_BEGIN_NAMESPACE

void MessageBox(const char *title, const char *message);

SOURIS_PLATFORM_END_NAMESPACE

#endif
