#ifndef SOURIS_CORE_DEFINES_HPP
#define SOURIS_CORE_DEFINES_HPP

# define SOURIS_CORE_NAMESPACE Core
# define SOURIS_CORE_BEGIN_NAMESPACE namespace SOURIS_CORE_NAMESPACE {
# define SOURIS_CORE_END_NAMESPACE }

#endif
