#ifndef SOURIS_CORE_DEFINES_HPP
#define SOURIS_CORE_DEFINES_HPP

# include "int_types.hpp"

# define SOURIS_CORE_NAMESPACE Core
# define SOURIS_CORE_BEGIN_NAMESPACE namespace SOURIS_CORE_NAMESPACE {
# define SOURIS_CORE_END_NAMESPACE }

# define SOURIS_PLATFORM_NAMESPACE Platform
# define SOURIS_PLATFORM_BEGIN_NAMESPACE namespace SOURIS_PLATFORM_NAMESPACE {
# define SOURIS_PLATFORM_END_NAMESPACE }

#endif
