#ifndef SOURIS_CORE_CLIENT_DELEGATOR_TYPES_PROCESS_START_PROCESS_START_HPP
#define SOURIS_CORE_CLIENT_DELEGATOR_TYPES_PROCESS_START_PROCESS_START_HPP

# include "core/client/delegator/delegator.hpp"

SOURIS_CORE_BEGIN_NAMESPACE
SOURIS_DELEGATOR_BEGIN_NAMESPACE

SOURIS_DECLARE_DELEGATOR(ProcessStart, Message::ProcessStart, SOURIS_PARAMETERS_WRAPPER(const Controller*, const nlohmann::json &data))

SOURIS_DELEGATOR_END_NAMESPACE
SOURIS_CORE_END_NAMESPACE

#endif
